"""py-powens — a modern, typed async Python SDK for the Powens API.

Public API:
- :class:`PowensClient` — main entry point
- exception hierarchy from :mod:`powens.exceptions`
- model types from :mod:`powens.models`
- optional :class:`RetryPolicy` and :class:`CircuitBreaker` protocol
"""

from powens._http.circuit import CircuitBreaker, NoOpCircuitBreaker
from powens._http.retry import RetryPolicy
from powens.client import PowensClient
from powens.exceptions import (
    PowensAuthError,
    PowensBadRequestError,
    PowensCircuitOpenError,
    PowensConflictError,
    PowensConnectionError,
    PowensError,
    PowensErrorCode,
    PowensHTTPError,
    PowensNotFoundError,
    PowensRateLimitError,
    PowensSerializationError,
    PowensServerError,
    PowensServiceUnavailableError,
)
from powens.models import (
    Account,
    AuthCode,
    AuthCodeAccess,
    AuthCodeRequestType,
    AuthCodeType,
    AuthScope,
    AuthServiceToken,
    AuthToken,
    AuthTokenExchange,
    AuthTokenType,
    AuthUrl,
    Balance,
    Connection,
    ConnectionState,
    Connector,
    ConnectUrl,
    Investment,
    InvestmentValue,
    Link,
    ManageUrl,
    OTPRequest,
    Page,
    PaginationLinks,
    PaymentWebviewUrl,
    PowensModel,
    ReconnectUrl,
    TokenTypeHeader,
    Transaction,
    TransactionType,
    User,
    UsersList,
    WebauthURL,
)

__version__ = "0.1.0"

__all__ = [
    "Account",
    "AuthCode",
    "AuthCodeAccess",
    "AuthCodeRequestType",
    "AuthCodeType",
    "AuthScope",
    "AuthServiceToken",
    "AuthToken",
    "AuthTokenExchange",
    "AuthTokenType",
    "AuthUrl",
    "Balance",
    "CircuitBreaker",
    "ConnectUrl",
    "Connection",
    "ConnectionState",
    "Connector",
    "Investment",
    "InvestmentValue",
    "Link",
    "ManageUrl",
    "NoOpCircuitBreaker",
    "OTPRequest",
    "Page",
    "PaginationLinks",
    "PaymentWebviewUrl",
    "PowensAuthError",
    "PowensBadRequestError",
    "PowensCircuitOpenError",
    "PowensClient",
    "PowensConflictError",
    "PowensConnectionError",
    "PowensError",
    "PowensErrorCode",
    "PowensHTTPError",
    "PowensModel",
    "PowensNotFoundError",
    "PowensRateLimitError",
    "PowensSerializationError",
    "PowensServerError",
    "PowensServiceUnavailableError",
    "ReconnectUrl",
    "RetryPolicy",
    "TokenTypeHeader",
    "Transaction",
    "TransactionType",
    "User",
    "UsersList",
    "WebauthURL",
    "__version__",
]
